version: '3.9'

services:
  flux:
    image: mvc-test
    build: .
    ports:
      - 8081:8080
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=reactive_db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - mongo-network
networks:
  mongo-network:
    external:
      name: mongo-network
